---
- name: Install packages on target hosts
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Check if Homebrew is installed on macOS
      command: brew --version
      register: brew_installed
      ignore_errors: true
      changed_when: false
      when: ansible_os_family == "Darwin"

    - name: Install Homebrew on macOS if not installed
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: ansible_os_family == "Darwin" and brew_installed.failed

    - name: Install VIM on macOS
      homebrew:
        name: vim
        state: present
      when: ansible_os_family == "Darwin"

    - name: Install Zsh on macOS
      homebrew:
        name: zsh
        state: present
      when: ansible_os_family == "Darwin"

    - name: Install VIM on Debian-based systems
      apt:
        name: vim
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Zsh on Debian-based systems
      apt:
        name: zsh
        state: present
      when: ansible_os_family == "Debian"

    - name: Install VIM on Red Hat-based systems
      yum:
        name: vim
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Zsh on Red Hat-based systems
      yum:
        name: zsh
        state: present
      when: ansible_os_family == "RedHat"

    - name: Verify VIM installation
      command: vim --version
      register: vim_version
      changed_when: false

    - name: Display VIM version
      debug:
        var: vim_version.stdout_lines[0]

    - name: Verify Zsh installation
      command: zsh --version
      register: zsh_version
      changed_when: false

    - name: Display Zsh version
      debug:
        var: zsh_version.stdout_lines[0]

    - name: Source .zshrc
      shell: zsh -c "source ~/.zshrc && zsh"
